### PR TITLE
Fancy installer

### PR DESCRIPTION
**Pull request by KampfCaspar**
... have a fancy installation

### CODE REVIEW

**Comment by AMD1212** [comment]
Wow, this looks really suffisticated. Sorry for beeing late with the merge, it took me a while to test it.

**Comment by AMD1212** [comment]
Wow, this looks really suffisticated. Sorry for beeing late with the merge, it took me a while to test it.

**Comment by AMD1212** [comment]
Wow, this looks really suffisticated. Sorry for beeing late with the merge, it took me a while to test it.

**Comment by AMD1212** [comment]
Wow, this looks really suffisticated. Sorry for beeing late with the merge, it took me a while to test it.

**Comment by AMD1212** [comment]
Wow, this looks really suffisticated. Sorry for beeing late with the merge, it took me a while to test it.

**Comment by KampfCaspar** [comment]
I'm sure there are enough edge cases and bugs...

**Comment by AMD1212** [comment]
Wow, this looks really sophisticated. Sorry for beeing late with the merge, it took me a while to test it.

**Comment by AMD1212** [comment]
Wow, this looks really sophisticated. Sorry for beeing late with the merge, it took me a while to test it.

**Comment by AMD1212** [comment]
Likely, but you made something complicated much better and easier.
Thanks for your contribution, it will be a lot of fun to try it out in our first "permanent" installation.

Sorry for the comment-spam -> my two main browsers seem to have problems with github...

**Pull request merged**
